version: "3"

services:
    app:
        image: gelato:latest
        volumes: 
           - ./allure-results:/wdio-tests/allure-results
           - ./wdio.conf.ts:/wdio-tests/wdio.conf.ts
           - ./package*.json:/wdio-tests/package*.json
           - ./wdio.conf.remote.ts:/wdio-tests/wdio.conf.remote.ts
        depends_on: 
            - selenium-hub
            - chrome
        links: 
            - chrome
        command: tail -f
        networks: 
            - testing-network

    chrome:
        image: selenium/node-chrome:4.0.0-beta-3-prerelease-20210321
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
            - SE_EVENT_BUS_HOST=selenium-hub
            - SE_EVENT_BUS_PUBLISH_PORT=4442
            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
        ports:
            - "6900:5900"
        networks:
            - testing-network

    selenium-hub:
        image: selenium/hub:4.0.0-beta-3-prerelease-20210321
        container_name: selenium-hub
        ports:
            - "4442:4442"
            - "4443:4443"
            - "4444:4444"
        networks: 
            - testing-network
networks: 
    testing-network:
        driver: bridge
